---
title: "4_PrepModelData"
output: html_document
date: "2026-04-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list=ls())
library(tidyverse)
library(conflicted)
conflicts_prefer(dplyr::select)
conflicts_prefer(dplyr::filter)
```

```{r load_data}

readRDS("mod_data/demog/mod_demog_data.rds") %>% list2env(.GlobalEnv)
microtopo <- read_csv("mod_data/microtopo/model_microtopo_25cm.csv",col_types = cols(plantID=col_character()))
mt_vars <- names(microtopo)[!names(microtopo) %in% c("site", "pop", "plantID", "elv_pt", "aspect.cat")]
clim <- read_csv("mod_data/full_climate.csv") 
clim_vars <- names(clim)[!names(clim) %in% c("site", "pop", "year")]

pred_vars <- c("log_size_t0",clim_vars,mt_vars)

pop_info <- read_csv("raw_data/pop_info/pop_info_slopeAspect.csv") %>%
  dplyr::select(pop,site, pop.set)

custom_scale_fun <- function(col){
  col_min <- min(col,na.rm=T)
  col_sd <- sd(col,na.rm=T)
  new_col <- (col - col_min)/col_sd
  return(new_col)
} 

surv_mod_data <- surv %>%
  left_join(microtopo, by = c("site", "pop", "plantID")) %>%
  left_join(clim, by = c("site", "pop", "year")) %>% 
  left_join(pop_info,by=c("pop","site")) %>%
  mutate(pop.set.year = paste0(pop.set,"_",year)) %>% 
  dplyr::select(-log_size) %>%
  na.omit() 

surv_mod_data_scaled <- surv_mod_data %>%
  mutate(across(all_of(pred_vars), ~ custom_scale_fun(.x)), 
         year = as.character(year))

growth_mod_data <- growth %>%
  left_join(microtopo, by = c("site", "pop", "plantID")) %>%
  left_join(clim, by = c("site", "pop", "year")) %>% 
  left_join(pop_info,by=c("pop","site")) %>%
  mutate(pop.set.year = paste0(pop.set,"_",year)) %>% 
  dplyr::select(-log_size) %>%
  na.omit() 

growth_mod_data_scaled <- growth_mod_data %>%
  mutate(across(all_of(pred_vars), ~ custom_scale_fun(.x)), 
         year = as.character(year))

repro_mod_data <- repro %>%
  left_join(microtopo, by = c("site", "pop", "plantID")) %>%
  left_join(clim, by = c("site", "pop", "year")) %>% 
  left_join(pop_info,by=c("pop","site")) %>%
  mutate(pop.set.year = paste0(pop.set,"_",year)) %>% 
  dplyr::select(-log_size) %>%
  na.omit() 

repro_mod_data_scaled <- repro_mod_data %>%
  mutate(across(all_of(pred_vars), ~ custom_scale_fun(.x)), 
         year = as.character(year))
 
nflrs_mod_data_scaled <- repro_mod_data %>%
  filter(flowered == 1) %>%
  mutate(across(all_of(pred_vars), ~ custom_scale_fun(.x)), 
         year = as.character(year)) %>% 
  mutate(total_flrs = round(total_flrs)) %>%
  na.omit() 
```

# set factor levels
```{r}
surv_mod_data_scaled$aspect.cat <- relevel(as.factor(surv_mod_data_scaled$aspect.cat), ref = "top")
growth_mod_data_scaled$aspect.cat <- relevel(as.factor(growth_mod_data_scaled$aspect.cat), ref = "top")
repro_mod_data_scaled$aspect.cat <- relevel(as.factor(repro_mod_data_scaled$aspect.cat), ref = "top")
nflrs_mod_data_scaled$aspect.cat <- relevel(as.factor(nflrs_mod_data_scaled$aspect.cat), ref = "top")

surv_mod_data_scaled$site <- relevel(as.factor(surv_mod_data_scaled$site), ref = "niwot")
growth_mod_data_scaled$site <- relevel(as.factor(growth_mod_data_scaled$site), ref = "niwot")
repro_mod_data_scaled$site <- relevel(as.factor(repro_mod_data_scaled$site), ref = "niwot")
nflrs_mod_data_scaled$site <- relevel(as.factor(nflrs_mod_data_scaled$site), ref = "niwot")
```

```{r write_data}
mod_data <- list(
  surv_mod_data = surv_mod_data,
  surv_mod_data_scaled = surv_mod_data_scaled,

  growth_mod_data = growth_mod_data,
  growth_mod_data_scaled = growth_mod_data_scaled,

  repro_mod_data = repro_mod_data,
  repro_mod_data_scaled = repro_mod_data_scaled,

  nflrs_mod_data_scaled = nflrs_mod_data_scaled
)

saveRDS(mod_data, "mod_data/all_mod_data.rds")
mean(surv_mod_data_scaled$gs_meanT_mean)
```

```{r save_scale_params}
all_num_vars <- c("log_size_t0", clim_vars, mt_vars)

surv_vars <- all_num_vars[all_num_vars %in% names(surv_mod_data)]
surv_scale_params <- data.frame(
  var = surv_vars,
  center = sapply(surv_vars, function(v) min(surv_mod_data[[v]], na.rm = TRUE)),
  scale = sapply(surv_vars, function(v) sd(surv_mod_data[[v]], na.rm = TRUE))
)

growth_vars <- all_num_vars[all_num_vars %in% names(growth_mod_data)]
growth_scale_params <- data.frame(
  var = growth_vars,
  center = sapply(growth_vars, function(v) min(growth_mod_data[[v]], na.rm = TRUE)),
  scale = sapply(growth_vars, function(v) sd(growth_mod_data[[v]], na.rm = TRUE))
)

repro_vars <- all_num_vars[all_num_vars %in% names(repro_mod_data)]
repro_scale_params <- data.frame(
  var = repro_vars,
  center = sapply(repro_vars, function(v) min(repro_mod_data[[v]], na.rm = TRUE)),
  scale = sapply(repro_vars, function(v) sd(repro_mod_data[[v]], na.rm = TRUE))
)

nflrs_mod_data <- repro_mod_data %>% filter(flowered == 1)
nflrs_vars <- all_num_vars[all_num_vars %in% names(nflrs_mod_data)]
nflrs_scale_params <- data.frame(
  var = nflrs_vars,
  center = sapply(nflrs_vars, function(v) min(nflrs_mod_data[[v]], na.rm = TRUE)),
  scale = sapply(nflrs_vars, function(v) sd(nflrs_mod_data[[v]], na.rm = TRUE))
)

scale_params <- list(
  surv = surv_scale_params,
  growth = growth_scale_params,
  repro = repro_scale_params,
  nflrs = nflrs_scale_params
)
saveRDS(scale_params, "mod_data/scale_params.rds")
```
